language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
install:
  # this fixes SemLock issues on travis
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm" 
  - "sudo apt-get install libzmq3-dev"
  - "make test_setup"
  - "python setup.py develop"
script: "make test"
